name: Build and Publish Native AOT Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: win-x64
            runner: windows-latest
          - platform: linux-x64
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Adjust as needed

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish Native AOT Binary for ${{ matrix.platform }}
        run: |
          dotnet publish -c Release -r ${{ matrix.platform }} \
            /p:PublishAot=true \
            /p:DebugType=None \
            /p:DebugSymbols=false \
            /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload Artifact for ${{ matrix.platform }}
        uses: actions/upload-artifact@v3
        with:
          name: native-aot-${{ matrix.platform }}
          path: ./bin/Release/net7.0/${{ matrix.platform }}/publish/
